POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "sarah22",
    "password": "mypassword",
    "name": "Sarah"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "sara2",
    "password": "2",
    "name": "Sarah"
}