POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My First Blog",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 23
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Arigatou",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": "12"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Happy Days 2",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 12121
}