POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My First Blog",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 23
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Arigatou",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": "12"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "hello hello",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 1,
    "userId": "64f5df37d58804060e3fe137"
}