POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My First Blog",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 23
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Arigatou",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": "12"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmFoIiwiaWQiOiI2NGY1ZGU4YzIyNzE4MTc1YzIxNjNkZjgiLCJpYXQiOjE2OTM4MzY5OTIsImV4cCI6MTY5Mzg0MDU5Mn0.mMpl6aurwz7LiE0e2lkTarktPv45N8AtJNPjucKAzro

{
    "title": "hello hello from sarah",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 1
}